/**
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* source: https://support.google.com/analytics/answer/9234069?hl=en */
const non_custom_events = [
    { event_name:"ad_click" },
    { event_name:"ad_exposure" },
    { event_name:"ad_impression" },
    { event_name:"ad_query" },
    { event_name:"ad_reward" },
    { event_name:"adunit_exposure" },
    { event_name:"app_clear_data" },
    { event_name:"app_exception" },
    { event_name:"app_remove" },
    { event_name:"app_store_refund" },
    { event_name:"app_store_subscription_cancel" },
    { event_name:"app_store_subscription_convert" },
    { event_name:"app_store_subscription_renew" },
    { event_name:"app_update" },
    { event_name:"click" },
    { event_name:"dynamic_link_app_open" },
    { event_name:"dynamic_link_app_update" },
    { event_name:"dynamic_link_first_open" },
    { event_name:"error" },
    { event_name:"file_download" },
    { event_name:"firebase_campaign" },
    { event_name:"firebase_in_app_message_action" },
    { event_name:"firebase_in_app_message_dismiss" },
    { event_name:"firebase_in_app_message_impression" },
    { event_name:"first_open" },
    { event_name:"first_visit" },
    { event_name:"form_start" },
    { event_name:"form_submit" },
    { event_name:"in_app_purchase" },
    { event_name:"notification_dismiss" },
    { event_name:"notification_foreground" },
    { event_name:"notification_open" },
    { event_name:"notification_receive" },
    { event_name:"os_update" },
    { event_name:"page_view" },
    { event_name:"screen_view" },
    { event_name:"scroll" },
    { event_name:"session_start" },
    { event_name:"user_engagement" },
    { event_name:"video_complete" },
    { event_name:"video_progress" },
    { event_name:"video_start" },
    { event_name:"view_search_results" },
    { event_name:"earn_virtual_currency" },
    { event_name:"generate_lead" },
    { event_name:"join_group" },
    { event_name:"login" },
    { event_name:"purchase" },
    { event_name:"refund" },
    { event_name:"search" },
    { event_name:"select_content" },
    { event_name:"share" },
    { event_name:"sign_up" },
    { event_name:"spend_virtual_currency" },
    { event_name:"tutorial_begin" },
    { event_name:"tutorial_complete" },
    { event_name:"add_payment_info" },
    { event_name:"add_shipping_info" },
    { event_name:"add_to_cart" },
    { event_name:"add_to_wishlist" },
    { event_name:"begin_checkout" },
    { event_name:"purchase" },
    { event_name:"refund" },
    { event_name:"remove_from_cart" },
    { event_name:"select_item" },
    { event_name:"select_promotion" },
    { event_name:"view_cart" },
    { event_name:"view_item" },
    { event_name:"view_item_list" },
    { event_name:"view_promotion" },
    { event_name:"earn_virtual_currency" },
    { event_name:"join_group" },
    { event_name:"level_end" },
    { event_name:"level_start" },
    { event_name:"level_up" },
    { event_name:"post_score" },
    { event_name:"select_content" },
    { event_name:"spend_virtual_currency" },
    { event_name:"tutorial_begin" },
    { event_name:"tutorial_complete" },
    { event_name:"unlock_achievement"},
    { event_name:"campaign_details"},
];
module.exports = { non_custom_events };